name: Showcase Submission
labels: ["showcase"]
description: If you have a shipped game, tool, or library using MonoGame on desktops, mobile, or consoles, you can use this submission to add your game to the MonoGame showcase.
body:
- type: checkboxes
  id: prerequisites
  attributes:
    label: Prerequisites
    options:
      - label: This game/tool/library is my own work
        required: true
      - label: This game/tool/library has shipped and is available for users.
        required: true
- type: dropdown
  id: type
  validations:
    required: true
  attributes:
    label: Type
    options:
      - Game
      - Library
      - Tool
- type: input
  id: name
  validations:
    required: true
  attributes:
    label: Name
    placeholder: My Game/Tool/Library
    description: What is the name of your game/tool/library?
- type: input
  id: url
  validations:
    required: true
  attributes:
    label: Url
    placeholder: https://example.com
    description: Please enter the URL you wouuld like users to be redirected to when they click your entry.
- type: textarea
  id: image
  validations:
    required: true
  attributes:
    label: Image
    description: |
      Please supply a 1920x1080 resolution gameplay screenshot.
      You can drag-and-drop it from a directory into this textbox or copy and paste the image here.
      If the file type is not supported, you can zip it then upload that instead.
- type: textarea
  id: logo
  validations:
    required: true
  attributes:
    label: Logo
    description: |
      Please supply a high resolution version of the logo on transparency. These are typically between 340x140 and 125x75 in size.
      We add a drop shadow to the logo in CSS automatically, so no need to include one in the logo.
      Please see the home and showcase pages for examples of how the screenshots and logos are used together.
      You can drag-and-drop it from a directory into this textbox or copy and paste the image here.
      If the file type is not supported, you can zip it then upload that instead.
- type: checkboxes
  id: tags
  attributes:
    label: Tags / Platforms
    description: |
      Please select the appropriate tags and supported platforms for your submission.
      For the platforms please select the platforms where MonoGame was used or is supported.
    options:
      - label: Desktop        
      - label: Mobile
      - label: Console
      - label: 2D
      - label: 3D
      - label: Windows
      - label: Mac
      - label: Linux
      - label: iOS
      - label: Android
      - label: WindowsPhone
      - label: NintendoSwitch
      - label: PlayStation4
      - label: PlayStation5
      - label: Xbox One
      - label: Xbox Series X/S
      - label: PSVita
      - label: Library
